### ISSUE TITLE
Scroll a whole "page" when clicking inside the scrollbar track

### ISSUE THREAD

**Issue by IBwWG** [IBwWG/FlxScrollableArea#3]

**Comment by larsiusprime** [comment]
Just wanted to say I'm interested in this new feature you're working on and would like to integrate it into flixel-ui when it's done :)

**Comment by IBwWG** [comment]
That's hilarious, I was just last night looking at implementing this next, after getting my todo list organized it was high on the list for my current project.  I was just a bit slow because our baby would not fall asleep unless in our arms, so I could only type with one hand!

**Comment by IBwWG** [comment]
TDD approach, I have written a failing test now for this.

**Comment by IBwWG** [comment]
Ah, there's also repeating page-scrolls when you hold down the button, on typical scrollbars.  This behaviour will be included.
